- name: Install required packages for libvirt/kvm
  ansible.builtin.package:
    name:
      - libvirt0
      - libvirt-clients
      - virtinst
      - libvirt-daemon-system
      - qemu-kvm
      - qemu-utils
      - libosinfo-bin
    state: present

- name: Set up usb passthrough udev rule
  ansible.builtin.lineinfile:
    path: /lib/udev/rules.d/51-qemu-usb-passthrough.rules
    line: >
      'SUBSYSTEM=="usb",
      ATTRS{idVendor}=="{{ item.vendor_id }}",
      ATTRS{idProduct}=="{{ item.model_id }}",
      OWNER="{{ item.username }}",
      GROUP="{{ item.username }}"'
    create: true
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ devices }}"
  notify:
    - Reload udev rules
    - Restart libvirtd

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers

- name: Set up qemu bridge acl
  ansible.builtin.lineinfile:
    path: /etc/qemu/bridge.conf
    line: 'allow br0'
    owner: root
    group: root
    mode: "0644"
    create: true

- name: Allow setuid for qemu-bridge-helper
  ansible.builtin.file:
    path: /usr/lib/qemu/qemu-bridge-helper
    state: file
    owner: root
    group: root
    mode: "04755"

- name: Add user to libvirt and kvm groups
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: libvirt,kvm,libvirt-qemu
    append: true
  loop: "{{ users }}"
