- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    home: /home/"{{ item.name }}"
    uid: "{{ item.uid }}"
    createhome: true
    state: present
  loop: "{{ users }}"

- name: Ensure home directory has proper permissions
  ansible.builtin.file:
    path: /home/{{ item.name }}
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0755'
    state: directory
  loop: "{{ users }}"

- name: Create hass .ssh folder
  ansible.builtin.file:
    path: /home/{{ item.name }}/.ssh
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0700'
  loop: "{{ users }}"

- name: Add ssh key to hass user
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', ssh_keys_path + '/' + item.name) }}"
    state: present
  when: item.name in lookup('fileglob', ssh_keys_path + '/*')
  loop: "{{ users }}"
